// Portfolio data — replace with API fetch later

export const portfolioData = [
  // ===== WORDPRESS ITEMS =====
  {
    id: 1,
    slug: "sajian-premium-kamu",
    title: "Sajian Premium Kamu",
    subtitle: "Sajian Vitatus Premium Kanou",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    category: "Food & Beverage",
    platform: "wordpress",
    type: "desktop",
    url: "https://example.com",
    description: "Platform catering premium dengan menu berkualitas tinggi",
    marqueeText: "sajianpremium.com",
    showcaseDescription: "Website catering premium yang menampilkan menu berkualitas tinggi dengan desain elegan dan modern.",
    frameworks: [
      { name: "WordPress", icon: "W", color: "bg-blue-700" },
      { name: "Elementor", icon: "E", color: "bg-pink-500" },
      { name: "WooCommerce", icon: "🛒", color: "bg-purple-600" },
    ],
  },
  {
    id: 2,
    slug: "haji-umrah",
    title: "Haji & Umrah",
    subtitle: "Bersama Kami Semua Lebih Mudah",
    image: "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=800&q=80",
    category: "Travel",
    platform: "wordpress",
    type: "desktop",
    url: "https://example.com",
    description: "Layanan travel haji dan umrah terpercaya",
    marqueeText: "hajiumrah.com",
    showcaseDescription: "Website layanan travel haji dan umrah dengan fitur booking online dan informasi paket lengkap.",
    frameworks: [
      { name: "WordPress", icon: "W", color: "bg-blue-700" },
      { name: "Elementor", icon: "E", color: "bg-pink-500" },
    ],
  },
  {
    id: 3,
    slug: "korean-street-food",
    title: "Pelopor Korean Street Food",
    subtitle: "Taste di Indonesia",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    category: "Food & Beverage",
    platform: "wordpress",
    type: "mobile",
    url: "https://example.com",
    description: "Authentic Korean street food experience",
    marqueeText: "koreanstreetfood.id",
    showcaseDescription: "Mobile-first website untuk Korean street food dengan menu interaktif dan sistem order online.",
    frameworks: [
      { name: "WordPress", icon: "W", color: "bg-blue-700" },
      { name: "Flavor Theme", icon: "🍜", color: "bg-orange-500" },
    ],
  },
  {
    id: 4,
    slug: "internet-solusi-it",
    title: "Internet Handal & Solusi IT",
    subtitle: "Untuk Bisnis Anda",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
    category: "Technology",
    platform: "wordpress",
    type: "desktop",
    url: "https://example.com",
    description: "Provider internet dan solusi IT untuk bisnis",
    marqueeText: "solusiit.com",
    showcaseDescription: "Website provider internet dan IT solutions dengan fitur cek coverage area dan paket berlangganan.",
    frameworks: [
      { name: "WordPress", icon: "W", color: "bg-blue-700" },
      { name: "Divi", icon: "D", color: "bg-purple-500" },
    ],
  },
  {
    id: 5,
    slug: "ecommerce-fashion",
    title: "E-Commerce Fashion",
    subtitle: "Belanja Online Mudah & Aman",
    image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&q=80",
    category: "E-Commerce",
    platform: "wordpress",
    type: "mobile",
    url: "https://example.com",
    description: "Platform belanja online fashion terlengkap",
    marqueeText: "fashionstore.id",
    showcaseDescription: "Platform e-commerce fashion mobile-friendly dengan katalog produk lengkap dan checkout aman.",
    frameworks: [
      { name: "WordPress", icon: "W", color: "bg-blue-700" },
      { name: "WooCommerce", icon: "🛒", color: "bg-purple-600" },
      { name: "Elementor", icon: "E", color: "bg-pink-500" },
    ],
  },
  {
    id: 6,
    slug: "fitness-tracker",
    title: "Aplikasi Fitness Tracker",
    subtitle: "Pantau Kesehatan Anda",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
    category: "Health & Fitness",
    platform: "wordpress",
    type: "mobile",
    url: "https://example.com",
    description: "Aplikasi tracking workout dan kesehatan",
    marqueeText: "fitnesstracker.id",
    showcaseDescription: "Website fitness tracker mobile-first dengan dashboard workout dan tracking progress kesehatan.",
    frameworks: [
      { name: "WordPress", icon: "W", color: "bg-blue-700" },
      { name: "BuddyBoss", icon: "B", color: "bg-green-600" },
    ],
  },
  {
    id: 7,
    slug: "real-estate-portal",
    title: "Real Estate Portal",
    subtitle: "Temukan Properti Impian",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    category: "Real Estate",
    platform: "wordpress",
    type: "desktop",
    url: "https://example.com",
    description: "Portal properti dengan listing terlengkap",
    marqueeText: "realestate.co.id",
    showcaseDescription: "Portal properti dengan listing lengkap, fitur pencarian canggih, dan virtual tour.",
    frameworks: [
      { name: "WordPress", icon: "W", color: "bg-blue-700" },
      { name: "Flavor Theme", icon: "🏠", color: "bg-teal-500" },
      { name: "IDX Plugin", icon: "📋", color: "bg-indigo-500" },
    ],
  },
  {
    id: 8,
    slug: "learning-management-system",
    title: "Learning Management System",
    subtitle: "Belajar Kapan Saja, Dimana Saja",
    image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80",
    category: "Education",
    platform: "wordpress",
    type: "desktop",
    url: "https://example.com",
    description: "Platform pembelajaran online interaktif",
    marqueeText: "learningms.com",
    showcaseDescription: "Platform LMS interaktif dengan fitur kelas online, quiz, dan sertifikat digital.",
    frameworks: [
      { name: "WordPress", icon: "W", color: "bg-blue-700" },
      { name: "LearnDash", icon: "📚", color: "bg-blue-500" },
      { name: "Elementor", icon: "E", color: "bg-pink-500" },
    ],
  },
  // ===== REACT ITEMS =====
  {
    id: 9,
    slug: "vit-catering",
    title: "VIT Catering",
    subtitle: "Premium Catering Service",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
    category: "Food & Beverage",
    platform: "react",
    type: "desktop",
    url: "https://vidicatering.com",
    description: "Website catering modern dengan Next.js dan React",
    marqueeText: "vidicatering.com",
    showcaseDescription: "Website catering premium dibangun dengan Next.js, menampilkan animasi modern dan performa tinggi.",
    frameworks: [
      { name: "Next.js", icon: "⚡", color: "bg-black" },
      { name: "React", icon: "⚛️", color: "bg-blue-500" },
      { name: "Tailwind CSS", icon: "🎨", color: "bg-cyan-500" },
    ],
  },
  {
    id: 10,
    slug: "portfolio-website",
    title: "Portfolio Website",
    subtitle: "Personal Developer Portfolio",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
    category: "Portfolio",
    platform: "react",
    type: "desktop",
    url: "https://example.com",
    description: "Portfolio website interaktif dengan animasi 3D",
    marqueeText: "myportfolio.dev",
    showcaseDescription: "Portfolio website dengan 3D marquee effects, smooth scrolling, dan animasi Framer Motion.",
    frameworks: [
      { name: "Next.js", icon: "⚡", color: "bg-black" },
      { name: "React", icon: "⚛️", color: "bg-blue-500" },
      { name: "Framer Motion", icon: "🎬", color: "bg-purple-500" },
    ],
  },
  {
    id: 11,
    slug: "dashboard-analytics",
    title: "Dashboard Analytics",
    subtitle: "Real-time Business Intelligence",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    category: "Technology",
    platform: "react",
    type: "desktop",
    url: "https://example.com",
    description: "Dashboard analytics real-time untuk monitoring bisnis",
    marqueeText: "analytics.app",
    showcaseDescription: "Dashboard analytics real-time dengan chart interaktif, data visualization, dan reporting otomatis.",
    frameworks: [
      { name: "React", icon: "⚛️", color: "bg-blue-500" },
      { name: "TypeScript", icon: "TS", color: "bg-blue-600" },
      { name: "Chart.js", icon: "📊", color: "bg-orange-500" },
    ],
  },
];

// UI/UX Portfolio Data
export const uiuxPortfolioData = [
  {
    id: 1,
    title: "Food Delivery App",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    category: "Mobile App",
    description: "Redesign UI/UX untuk aplikasi food delivery dengan fokus pada user flow yang lebih intuitif.",
    tools: ["Figma", "Maze", "Miro"],
    caseStudyUrl: "https://example.com",
  },
  {
    id: 2,
    title: "Banking Dashboard",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    category: "Dashboard",
    description: "Dashboard banking dengan data visualization yang clean dan navigasi yang efisien.",
    tools: ["Figma", "Adobe XD"],
    caseStudyUrl: "https://example.com",
  },
  {
    id: 3,
    title: "E-Learning Platform",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80",
    category: "Web App",
    description: "Platform e-learning dengan gamification elements dan progress tracking.",
    tools: ["Figma", "Protopie", "Hotjar"],
    caseStudyUrl: "https://example.com",
  },
  {
    id: 4,
    title: "Health & Wellness App",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
    category: "Mobile App",
    description: "Aplikasi kesehatan dengan fitur tracking, reminder, dan konsultasi dokter online.",
    tools: ["Figma", "Maze"],
    caseStudyUrl: "https://example.com",
  },
  {
    id: 5,
    title: "Project Management Tool",
    image: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&q=80",
    category: "Web App",
    description: "Tool manajemen project dengan kanban board, timeline, dan team collaboration.",
    tools: ["Figma", "FigJam", "Miro"],
    caseStudyUrl: "https://example.com",
  },
  {
    id: 6,
    title: "Analytics Dashboard",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    category: "Dashboard",
    description: "Dashboard analytics real-time dengan chart interaktif dan custom reporting.",
    tools: ["Figma", "Adobe XD"],
    caseStudyUrl: "https://example.com",
  },
];

// Graphic Design Portfolio Data
export const graphicDesignData = [
  {
    id: 1,
    title: "Artisan Coffee Branding",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80",
    category: "Branding",
    description: "Complete brand identity untuk artisan coffee shop.",
  },
  {
    id: 2,
    title: "Music Festival Poster",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    category: "Print",
    description: "Poster series untuk festival musik tahunan.",
  },
  {
    id: 3,
    title: "Fashion Brand Identity",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80",
    category: "Branding",
    description: "Logo dan brand identity untuk fashion brand lokal.",
  },
  {
    id: 4,
    title: "Social Media Campaign",
    image: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&q=80",
    category: "Social Media",
    description: "Social media content design untuk kampanye produk.",
  },
  {
    id: 5,
    title: "Restaurant Menu Design",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    category: "Print",
    description: "Menu design untuk restoran fine dining.",
  },
  {
    id: 6,
    title: "Tech Startup Branding",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80",
    category: "Branding",
    description: "Full branding package untuk tech startup.",
  },
  {
    id: 7,
    title: "Instagram Content Kit",
    image: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=800&q=80",
    category: "Social Media",
    description: "Template kit untuk Instagram feed dan stories.",
  },
  {
    id: 8,
    title: "Product Packaging",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    category: "Print",
    description: "Packaging design untuk produk skincare.",
  },
];
